version: "3.9"

services:
  graphql-sample-mysql-db:
    container_name: mysql_backend_db
    image: mysql:latest
    environment:
      TZ: ${TIME_ZONE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_HOST: ${MYSQL_HOST}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - "${DB_DOCKER_PORT}:3306"
    volumes:
      - ./db/data:/var/lib/mysql
      - ./db/conf:/etc/mysql/conf.d
      - ./db/log:/var/log
    env_file:
      - .env
    restart: always

  phpmyadmin:
    container_name: backend_phpmyadmin
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOSTS=mysql_backend_db
      - PMA_USER=root
      - PMA_PASSWORD=${MYSQL_ROOT_PASSWORD}
    ports:
     - ${ADMIN_DOCKER_PORT}:80
    env_file:
      - .env
    restart: always

