version: '3.9'

services:
  graphql-sample-mongo-db:
    image: mongo:latest
    container_name: mongo_db
    environment:
      - AUTH=no
    command: [--replSet, my-replica-set, --noauth, --bind_ip_all]
    ports:
      - ${MONGO_PORT}:27017
    healthcheck:
      test: mongosh mongo-init.js
      interval: 10s
      start_period: 30s
    volumes:
      - ./db/init/db_init.js:/mongo-init.js
      - ./db/init/config.js:/config.js
      - ./db/data:/data/db
      - ./db/config:/data/configdb
    env_file:
      - .env
    restart: always

  mongo-express:
    image: mongo-express
    container_name: mongo_express
    ports:
      - ${EXPRESSPORT}:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${ROOT_USERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${ROOT_PASSWORD}
      ME_CONFIG_MONGODB_SERVER: graphql-sample-mongo-db
      ME_CONFIG_BASICAUTH_USERNAME: ${BASICAUTH_USER}
      ME_CONFIG_BASICAUTH_PASSWORD: ${BASICAUTH_PASSWD}
    env_file:
      - .env
    depends_on:
      - graphql-sample-mongo-db 
    restart: always
